### PR TITLE
Allow NNlib 0.9

### PR DESCRIPTION
**Pull request by mcabbott**
This will allow use with Flux 0.14, which lets you not load CUDA on 1.9.

### CODE REVIEW

**Comment by mcabbott** [comment]
Do you plan to tag a release soon? I see some changes for 1.9 but haven't looked closely.

**Comment by dfdx** [comment]
Yes, as soon as I get to the computer (today).

**Comment by dfdx** [comment]
Version 0.8.4 released!

**Comment by mcabbott** [comment]
Thanks!

**Pull request merged**
